### ISSUE TITLE
SRS - Introduction

### ISSUE THREAD

**Issue by nsgnn** [ChristopherGerbi/capstone#2]
_Subissue of #1_ 

- Purpose of This Document
  - State the purpose of this document and specify the intended readership.
- References
  - Provide a list of all applicable and referenced documents and other media (e.g., the Somerville text, UML references, documents provided by the customer, websites).  For each reference, provide the title, author, publisher (if applicable), date, and URL (for websites).
- Purpose of the Product
  - This section provides a short description of the user’s work and the situation that triggered the need for the product.  It describes the task(s) that the user wants to accomplish with the delivered product.  It is the product justification.
- Product Scope
  - This section identifies the boundary between the system under development and the outside world.  That is, it identifies what is included in the system and what is not. Typically, a context diagram best describes the boundary.  However, because the systems in this class are small, we will use a combination top-level use case and context diagram.   In addition to referring the reader to the diagram, give a brief summary of how it illustrates the system’s scope.  Make sure to number the use cases in the diagram.

**Comment by AlexThacker** [comment]
Purpose of Doc/Product (1.1, 1.3) have been written.
