### ISSUE TITLE
SRS - Non-Functional Requirements

### ISSUE THREAD

**Issue by nsgnn** [ChristopherGerbi/capstone#4]
_subissue of #1_
- Each NFR must include the following:
  - Unique ID Number
  - Priority: 1 (low) to 5 (high)
  - Description
  - Tests for system and acceptance testing
    - These shall be numbered in correspondence to the NFR ID number

**Comment by nsgnn** [comment]
I will work on deriving any and all NFR from the first half of user stories. @AlexThacker will work on the second half. Afterwards, we will review each others work before completing this subissue.

**Comment by AlexThacker** [comment]
Entered 4 new NFR and split one created by Nathan which contained a conjunction.

They were reviewed and edited if needed by Nathan.
